services:
  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: prometheus
    restart: unless-stopped
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "${HOST_BIND_ADDRESS:-127.0.0.1}:9090:9090"
    networks: [monitoring]

  alertmanager:
    image: prom/alertmanager:v0.30.0
    container_name: alertmanager
    restart: unless-stopped
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
      - --storage.path=/alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - alertmanager_data:/alertmanager
    ports:
      - "${HOST_BIND_ADDRESS:-127.0.0.1}:9093:9093"
    networks: [monitoring]

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: node-exporter
    restart: unless-stopped
    # 采集宿主机指标（Linux 常用方式）
    pid: host
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro #,rslave
    networks: [monitoring]

  grafana:
    image: grafana/grafana:12.3
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-Admin123}
    volumes:
      - grafana_data:/var/lib/grafana
      - ../../grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "${HOST_BIND_ADDRESS:-127.0.0.1}:3000:3000"
    networks: [monitoring]
    depends_on:
      - prometheus

networks:
  monitoring:

volumes:
  prometheus_data:
  alertmanager_data:
  grafana_data:
