#!/usr/bin/env bash
set -ueo pipefail

export ME_CONFIG_BASICAUTH_USERNAME="${ME_CONFIG_BASICAUTH_USERNAME:-admin}"
export ME_CONFIG_BASICAUTH_PASSWORD="${ME_CONFIG_BASICAUTH_PASSWORD:-Admin123}"
export ME_CONFIG_MONGODB_SERVER="${ME_CONFIG_MONGODB_SERVER:-mongo}"
export ME_CONFIG_MONGODB_ADMINUSERNAME="${ME_CONFIG_MONGODB_ADMINUSERNAME:-admin}"
export ME_CONFIG_MONGODB_ADMINPASSWORD="${ME_CONFIG_MONGODB_ADMINPASSWORD:-Admin123}"

if [[ "$ME_CONFIG_MONGODB_SERVER" == mongo || "$ME_CONFIG_MONGODB_SERVER" == mongo7 ]]; then
  set -- --link "$ME_CONFIG_MONGODB_SERVER:$ME_CONFIG_MONGODB_SERVER"
else
  set --
fi

docker run -d \
--name mongo-express \
--hostname mongo-express \
-p "${HOST_BIND_ADDRESS:-127.0.0.1}:8081:8081" \
"$@" \
--restart=unless-stopped \
--env ME_CONFIG_BASICAUTH_USERNAME \
--env ME_CONFIG_BASICAUTH_PASSWORD \
--env ME_CONFIG_MONGODB_SERVER \
--env ME_CONFIG_OPTIONS_NO_DELETE=true \
--env ME_CONFIG_MONGODB_ADMINUSERNAME \
--env ME_CONFIG_MONGODB_ADMINPASSWORD \
mongo-express:1.0.2
